### ISSUE TITLE
An unhandled error was encountered while prettifying. Care to file a bug? 

### ISSUE THREAD

**Issue by chenfeifly88** [victorporof/Sublime-HTMLPrettify#449] opened 2017-07-18 08:38 UTC
An unhandled error was encountered while prettifying. Care to file a bug?

**Comment by victorporof** [comment] 2017-07-18 12:03
Duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/442

**Closed by victorporof** 2017-07-18 12:03 UTC
