### ISSUE TITLE
Can't "Hide Others" on Mac

### ISSUE THREAD

**Issue by jeffhatz** [victorporof/Sublime-HTMLPrettify#660] opened 2019-01-03 02:22 UTC
On a Mac, pressing ⌘+⌥+H hides all apps but the active one. This behavior is broken with this plugin, because it hijacks that shortcut and doesn't pass it to the system. This has long been an annoyance, and just now discovered it's this plugin. I'd like to keep using it, but can't now that I know it's affecting a system-wide shortcut I use all the time.

**Comment by jeffhatz** [comment] 2019-01-03 02:30
Found a manual fix: `Tools > HTML/CSS/JS Prettify > Keyboard Shortcuts - Default` and reassign the shortcuts. I did +p instead of +h.

Though it took forever for me to find out this plugin was the reason why. Default should be changed so others don't have to deal with the same bug.

**Comment by victorporof** [comment] 2019-02-10 17:21
Dupe of #537

**Closed by victorporof** 2019-02-10 17:21 UTC
