### ISSUE TITLE
an unhandled error was encountered while prettifying. care to file a bug

### ISSUE THREAD

**Issue by yellow10086** [victorporof/Sublime-HTMLPrettify#438] opened 2017-07-18 02:19 UTC
an unhandled error was encountered while prettifying. care to file a bugan unhandled error was encountered while prettifying. care to file a bug

**Comment by victorporof** [comment] 2017-07-18 07:37
Duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/440

**Closed by victorporof** 2017-07-18 07:37 UTC
