### ISSUE TITLE
I have a bug in the prettifier

### ISSUE THREAD

**Issue by Lhace** [victorporof/Sublime-HTMLPrettify#608] opened 2018-10-01 08:08 UTC
the Prettifier don't work with Sublime editor

**Comment by victorporof** [comment] 2018-10-01 08:12
What's the output in sublime's console?

**Comment by victorporof** [comment] 2018-10-01 11:28
Likely a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/610

**Closed by victorporof** 2018-10-01 11:28 UTC
