### ISSUE TITLE
Handlebars Partials On Separate Lines

### ISSUE THREAD

**Issue by loganknecht** [victorporof/Sublime-HTMLPrettify#204] opened 2015-03-12 21:43 UTC
Hey there!

Absolutely LOVE this plug-in however, I'm having an issue in a file that that is composed of just handlebar syntax.

The file is this:
```html
{{#extend "layouts/pricing-plans"}}
    <!-- .... -->
    {{#content "content" mode="replace" }}
        {{> templates/partials/pricing/business-pricing/pricing-table }}
        {{> templates/partials/registration/registration_form }}
        {{> templates/partials/pricing/business-pricing/pricing-features }}
        {{> templates/partials/pricing/business-pricing/common-questions }}
    {{/content}}
    <!-- .... -->
{{/extend}}
```

I have prettify set to format on save, but when I save the file it changes it to this:
```html
{{#extend "layouts/pricing-plans"}}
    <!-- .... -->
    {{#content "content" mode="replace" }}
        {{> templates/partials/pricing/business-pricing/pricing-table }} {{> templates/partials/registration/registration_form }} {{> templates/partials/pricing/business-pricing/pricing-features }} {{> templates/partials/pricing/business-pricing/common-questions }}
    {{/content}}
    <!-- .... -->
{{/extend}}
```
Is there a feature I'm overlooking that will rectify this? Or may I put in a request for a feature that will set partials not to be on the same line?

**Comment by victorporof** [comment] 2015-03-17 20:43
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/163

**Closed by victorporof** 2015-03-17 20:43 UTC

**Comment by wkerswell** [comment] 2015-04-23 13:06
I have also come across this and would also like a fix.

**Comment by ldexterldesign** [comment] 2015-09-10 21:35
FYI https://twitter.com/ldexterldesign/status/642088367316946944

Regards
