### ISSUE TITLE
CSS: it keeps adding a newline before a comment.

### ISSUE THREAD

**Issue by 8lall0** [victorporof/Sublime-HTMLPrettify#504] opened 2017-11-09 08:48 UTC
When i comment something in my css files, like that
`/* Fira sans */`
It adds a newline before the line, even if there is another newline.

**Comment by danielhickman** [comment] 2017-11-09 20:20
Related: https://github.com/victorporof/Sublime-HTMLPrettify/issues/492

**Comment by victorporof** [comment] 2018-05-23 09:10
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/492

**Closed by victorporof** 2018-05-23 09:10 UTC
