### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by qingtian9581** [victorporof/Sublime-HTMLPrettify#564] opened 2018-05-21 05:56 UTC
设置了node还报错？

**Comment by yingjie2219** [comment] 2018-05-22 12:09
me too，the error: 'a runtime error was encountered in the prettifer'.
My mac osx is 10+ and My windows is 10(x64), the same error!

**Comment by victorporof** [comment] 2018-05-23 08:55
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 08:55 UTC
