### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by deng0928** [victorporof/Sublime-HTMLPrettify#552] opened 2018-05-10 06:38 UTC
### HTMLPrettify diagnostics begin ###
[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"html": {"allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"], "allowed_file_syntaxes": ["html", "xml"], "disallowed_file_patterns": []}, "js": {"allowed_file_extensions": ["js"], "allowed_file_syntaxes": ["javascript", "ecma"], "disallowed_file_patterns": []}, "json": {"allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"], "allowed_file_syntaxes": ["json"], "disallowed_file_patterns": []}, "css": {"allowed_file_extensions": ["css", "scss", "sass", "less"], "allowed_file_syntaxes": ["css", "sass", "less"], "disallowed_file_patterns": []}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/HTML/HTML.sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: C:\Users\dengzhiling\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\57e25e03-a8da-41f5-a7b0-7fa4b52f4da7
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: D:\test\index.html
[HTMLPrettify] Config extra lookup paths: C:\Users\dengzhiling\AppData\Roaming\Sublime Text 3\Packages\User,C:\Users\dengzhiling\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["D:\\test","D:","C:\\Users\\dengzhiling","C:\\Users\\dengzhiling\\AppData\\Roaming\\Sublime Text 3\\Packages\\User","C:\\Users\\dengzhiling\\AppData\\Roaming\\Sublime Text 3\\Packages\\HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: C:\Users\dengzhiling\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\.jsbeautifyrc.defaults.json
[HTMLPrettify] Attempting to parse file: D:\test\.editorconfig
[HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":"2","indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":false,"indent_inner_html":false,"indent_scripts":"keep","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"charset":"utf-8","end_of_line":"lf","trim_trailing_whitespace":true},"css":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":"2","indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true,"charset":"utf-8","end_of_line":"lf","trim_trailing_whitespace":true},"js":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":"2","indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false,"charset":"utf-8","end_of_line":"lf","trim_trailing_whitespace":true},"json":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":"2","indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false,"charset":"utf-8","end_of_line":"lf","trim_trailing_whitespace":true}}
[HTMLPrettify] Attempting to prettify what seems to be a HTML file.
### HTMLPrettify prettified code begin ###
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>test</title>
</head>

<body>
  <div id="app"></div>
  
</body>

</html>

### HTMLPrettify prettified code end ###

**Comment by victorporof** [comment] 2018-05-23 08:56
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 08:56 UTC
