### ISSUE TITLE
 'module' object has no attribute 'getoutput'

### ISSUE THREAD

**Issue by lingzhuzi** [victorporof/Sublime-HTMLPrettify#276] opened 2016-01-20 09:06 UTC
mac 10.9.2
node v5.4.1   path: /usr/local/bin/node
Python 2.7.5
Sublime Text 2  Version 2.0.2, Build 2221
```
Using node.js path on 'osx': /usr/local/bin/node
Unexpected error(<type 'exceptions.AttributeError'>): 'module' object has no attribute 'getoutput'
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./HTMLPrettify.py", line 48, in run
    print(self.get_output_diagnostics(output))
  File "./HTMLPrettify.py", line 110, in get_output_diagnostics
    index = output.find(OUTPUT_VALID)
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by aclewis182** [comment] 2016-01-25 21:48
I have the same issue (and system configuration).  I've just spent the last 3 hours walking though the code and learned a few things about this issue.

From what I can tell, it's due to 'output' not being populated (duh) but it caused by a failure on line 202 of **HTMLPrettify.py**: `return commands.getoutput(run)`

This issue can be quickly be reproduced by testing `getoutput` at the top of the file:
```
import sublime, sublime_plugin
import os, sys, subprocess, codecs, webbrowser

try:
  import commands
  print commands.getoutput('ls -alh')
except ImportError:
  pass

PLUGIN_FOLDER = os.path.dirname(os.path.realpath(__file__))
...
``` 
Which throws this error when the library is loaded:
```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./HTMLPrettify.py", line 11, in <module>
    print commands.getoutput('ls -alh')
AttributeError: 'module' object has no attribute 'getoutput'
```

I have tested that the same command works in the python shell with no trouble.
```
$ python
Python 2.7.11 (default, Jan 22 2016, 08:28:37) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import commands
>>> print commands.getoutput('ls -alh')
total 152
drwxr-xr-x  17 alewis  staff   578B Jan 25 15:37 .
drwxr-xr-x  60 alewis  staff   2.0K Jan 25 12:35 ..
-rw-r--r--   1 alewis  staff    16B Aug  5 20:56 .gitignore
-rw-r--r--   1 alewis  staff   4.1K Dec  2 13:31 .jsbeautifyrc
-rw-r--r--   1 alewis  staff     0B Aug  5 20:56 .no-sublime-package
-rw-r--r--   1 alewis  staff   506B Aug  5 20:56 Context.sublime-menu
-rw-r--r--   1 alewis  staff   393B Aug  5 20:56 Default (Linux).sublime-keymap
-rw-r--r--   1 alewis  staff   398B Aug  5 20:56 Default (OSX).sublime-keymap
-rw-r--r--   1 alewis  staff   394B Aug  5 20:56 Default (Windows).sublime-keymap
-rw-r--r--   1 alewis  staff   7.8K Jan 25 15:37 HTMLPrettify.py
-rw-r--r--   1 alewis  staff   8.4K Jan 25 15:37 HTMLPrettify.pyc
-rw-r--r--   1 alewis  staff   473B Aug  5 20:56 HTMLPrettify.sublime-commands
-rw-r--r--   1 alewis  staff   599B Jan 25 14:32 HTMLPrettify.sublime-settings
-rw-r--r--   1 alewis  staff   1.3K Aug  5 20:56 Main.sublime-menu
-rw-r--r--   1 alewis  staff    10K Aug  5 20:56 README.md
-rw-r--r--   1 alewis  staff   258B Aug  5 20:56 package-metadata.json
drwxr-xr-x   4 alewis  staff   136B Jan 25 15:33 scripts
>>> 
```

**Comment by aclewis182** [comment] 2016-01-25 21:55
Additional Information.

Looking at the module contents (dir) of the `commands` module from within HTMLPrettify yields:
```
('dir', ['GitAddChoiceCommand', 'GitAddSelectedHunkCommand', 'GitAnnotateCommand', 'GitAnnotationListener', 'GitBlameCommand', 'GitBranchCommand', 'GitBranchStatusCommand', 'GitBranchStatusListener', 'GitCheckoutTagCommand', 'GitClearAnnotationCommand', 'GitCommitAmendCommand', 'GitCommitCommand', 'GitCommitHistoryCommand', 'GitCommitMessageListener', 'GitCommitSelectedHunk', 'GitCustomCommand', 'GitDeleteBranchCommand', 'GitDeleteTagCommand', 'GitDiff', 'GitDiffAllCommand', 'GitDiffCommand', 'GitDiffCommit', 'GitDiffCommitCommand', 'GitDocumentCommand', 'GitFlowCommand', 'GitFlowFeatureFinishCommand', 'GitFlowFeatureStartCommand', 'GitFlowHotfixFinishCommand', 'GitFlowHotfixStartCommand', 'GitFlowReleaseFinishCommand', 'GitFlowReleaseStartCommand', 'GitGitkCommand', 'GitGotoCommit', 'GitGotoDiff', 'GitGraph', 'GitGraphAllCommand', 'GitGraphCommand', 'GitGuiCommand', 'GitInit', 'GitInitCommand', 'GitLog', 'GitLogAllCommand', 'GitLogCommand', 'GitMergeCommand', 'GitNewBranchCommand', 'GitNewTagCommand', 'GitOpenFileCommand', 'GitOpenModifiedFilesCommand', 'GitPullCurrentBranchCommand', 'GitPullRebaseCommand', 'GitPushCurrentBranchCommand', 'GitQuickCommitCommand', 'GitRawCommand', 'GitResetHardHeadCommand', 'GitResetHead', 'GitResetHeadAllCommand', 'GitResetHeadCommand', 'GitScratchOutputCommand', 'GitShow', 'GitShowAllCommand', 'GitShowCommand', 'GitShowTagsCommand', 'GitStashApplyCommand', 'GitStashCommand', 'GitStashDropCommand', 'GitStashListCommand', 'GitStatusCommand', 'GitTextCommand', 'GitToggleAnnotationsCommand', 'GitTrackRemoteBranchCommand', 'GitUpdateIgnoreCommand', 'GitWindowCommand', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'absolute_import', 'codecs', 'division', 'do_when', 'functools', 'git_root', 'git_root_exist', 'goto_xy', 'history', 'mod', 'mod_prefix', 'mods_load_order', 'os', 'plugin_file', 'plugins', 'print_function', 're', 'reload_mods', 'reloaded', 'sublime', 'sublime_plugin', 'suffix', 'sys', 'tempfile', 'unicode_literals', 'view_contents'])
```

Rather than the Standard library's:
```
>>> print(dir(commands))
['__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'getoutput', 'getstatus', 'getstatusoutput', 'mk2arg', 'mkarg']
```

**Comment by Tailszefox** [comment] 2016-01-25 22:08
Looks like this is due to a conflict with the "Git" package, probably because that package contains a file called `commands.py`. So `import commands` just imports that file instead of importing the `commands` module.

Disabling the Git package seems to work, but obviously you then lose all Git commands.

As it stands, I don't know if the problem lies with the Git package (which means that bug report should be moved to [its repository](https://github.com/kemayo/sublime-text-git)) or if something can be done to prevent that conflict directly from HTMLPrettify.

**Comment by aclewis182** [comment] 2016-01-25 22:33
Just confirmed the same thing.  However disabling didn't; I had to completely remove it.

**Comment by aclewis182** [comment] 2016-01-25 22:52
At a higher level, it would be nice if Sublime protected scope some how; lacking ideas at the moment tho.  I've created a ticket in the git plug-in's project to hopefully address it in the short term.

**Comment by kemayo** [comment] 2016-01-26 23:30
ST3 protects scope, by forcing all packages into their own top-level module. ST2, however, has scope issues.

**Comment by lingzhuzi** [comment] 2016-01-29 07:58
@Tailszefox I removed the Git package, and it seems worked. Thanks !

**Comment by kemayo** [comment] 2016-01-29 15:30
Git package has been updated to not cause this anymore, incidentally.

**Comment by victorporof** [comment] 2016-04-08 05:49
@kemayo nice! closing this then

**Closed by victorporof** 2016-04-08 05:49 UTC
