### ISSUE TITLE
PretifyCode Run Time Error since installation of node.js version v10.1.0

### ISSUE THREAD

**Issue by EwanEwart** [victorporof/Sublime-HTMLPrettify#558] opened 2018-05-16 19:21 UTC
A run-time error was encountered in the prettify sublime-text plug-in.
See the (Python) console output for more information: 

Node.js encountered a runtime error: (node:19325) ExperimentalWarning: The fs.promises API is experimental

Since installation of node.js **version v10.1.0** !
Since installation of **node.js version v10.1.0** !
**Since installation of node.js version v10.1.0 !**

### HTMLPrettify diagnostics begin ###
[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"html": {"disallowed_file_patterns": [], "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"], "allowed_file_syntaxes": ["html", "xml"]}, "json": {"disallowed_file_patterns": [], "allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"], "allowed_file_syntaxes": ["json"]}, "css": {"disallowed_file_patterns": [], "allowed_file_extensions": ["css", "scss", "sass", "less"], "allowed_file_syntaxes": ["css", "sass", "less"]}, "js": {"disallowed_file_patterns": [], "allowed_file_extensions": ["js"], "allowed_file_syntaxes": ["javascript", "ecma"]}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/HTML/HTML.sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: /home/ewan/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/ee48fc9c-bdfc-467b-a3c4-7c380ca70a97
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: /media/ewan/seagate1/RED/EE/development/ee/js/alarmClock.01/alarmClock.html
[HTMLPrettify] Config extra lookup paths: /home/ewan/.config/sublime-text-3/Packages/User,/home/ewan/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["/media/ewan/seagate1/RED/EE/development/ee/js/alarmClock.01","/media/ewan/seagate1/RED/EE/development/ee/js","/media/ewan/seagate1/RED/EE/development/ee","/media/ewan/seagate1/RED/EE/development","/media/ewan/seagate1/RED/EE","/media/ewan/seagate1/RED","/media/ewan/seagate1","/media/ewan","/media","/home/ewan","/home/ewan/.config/sublime-text-3/Packages/User","/home/ewan/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: /home/ewan/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc.defaults.json
[HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":false,"indent_inner_html":false,"indent_scripts":"keep","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false}},"css":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"json":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false}}
[HTMLPrettify] Attempting to prettify what seems to be a HTML file.
### HTMLPrettify prettified code begin ###
<!DOCTYPE html>
<html>

<head>
    <title>AlarmClock</title>
    <style type="text/css" media="screen" src="alarmClock.css">

    </style>
    <script src="alarmClock.js" charset="utf-8"></script>
</head>

<body>
    <form action="" method="">
        <div id="jsalarmclock">
            <div>
                <div class="leftcolumn">Current Time:</div> <span id="jsalarm_ct" style="letter-spacing: 2px"></span></div>
            <div>
                <div class="leftcolumn">Set Alarm:</div> <span><select></select> Hour</span> <span><select></select> Minutes</span> <span><select></select> Seconds</span></div>
            <div>
                <div class="leftcolumn">Set Alarm Action:</div>
                <input type="text" id="musicloc" size="55" value="http://www.youtube.com/watch?v=v1zY_tV5kaQ" /> <span style="font: normal 11px Tahoma">*Location of page to launch</span></div>
            <input type="submit" value="Set Alarm!" id="submitbutton" />
            <input type="reset" value="reset" id="resetbutton" />
        </div>
    </form>
    <script type="text/javascript">
    jsalarm.init()
    </script>
</body>

</html>

**Comment by orliesaurus** [comment] 2018-05-17 22:09
Have the same issue, updated node and this stopped working

**Comment by victorporof** [comment] 2018-05-23 08:55
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 08:55 UTC
