### ISSUE TITLE
An unhandled error

### ISSUE THREAD

**Issue by imdadshafi** [victorporof/Sublime-HTMLPrettify#503] opened 2017-11-05 15:35 UTC
when i select HTMLprettify. I facing this error.

_An unhandled error was encountered while prettifying. See the console output for more information. Do you wish to file a bug?_

**Comment by victorporof** [comment] 2018-05-23 09:09
Probably a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 09:09 UTC
