### ISSUE TITLE
Make Plugin Work in Paths that include UTF8 characters

### ISSUE THREAD

**Issue by bf** [victorporof/Sublime-HTMLPrettify#266] opened 2015-11-10 15:00 UTC
According to a comment on issue #107 ( https://github.com/victorporof/Sublime-HTMLPrettify/issues/107#issuecomment-142729775 ), this plugin doesn't handle UTF8 characters in its path very well. Please fix this.

**Comment by bf** [comment] 2015-11-10 15:01
Thanks to @scorpiohjx for raising this issue through his comment.

**Comment by bf** [comment] 2015-11-10 15:02
Might be same as issue #126

**Comment by victorporof** [comment] 2015-11-11 19:15
No, this project is not dead. It's an issue that is proving surprisingly difficult to fix in a cross platform all-locales all-charsets way. Feel free to contribute.

**Comment by victorporof** [comment] 2015-11-11 19:15
Dupe of #126

**Closed by victorporof** 2015-11-11 19:15 UTC
