### ISSUE TITLE
spontan throw bug 

### ISSUE THREAD

**Issue by mrG0bliN** [victorporof/Sublime-HTMLPrettify#566] opened 2018-05-21 15:43 UTC
name: stylus-loader.js
```
module.exports = (combiner, src, dest, _run, inDevApps, isDevelopment,  cssImageLink, cssFontsLink, inPubCss, errorConfig, __cfg) =>
() => 		combiner(
	src(`${inDevApps}/stylus/**/connect.styl`),
	_run.if(isDevelopment, _run.sourcemaps.init()),
	_run.stylus(__cfg),
	_run.autoprefixer({ browsers: ['last 5 version'] }),
	_run.if(isDevelopment, _run.sourcemaps.write()),
	_run.urlReplace({ prepend: cssImageLink }),
	_run.urlReplace(cssFontsLink),
	_run.rename('global.css'),
	dest(inPubCss)).on('error',
	_run.notify.onError((err) => errorConfig('Stylus', 'ошибка синтаксиса', err)));


```
i pressed hotkey and throw bug D:

preview 
![alt](http://joxi.ru/nAyMaxBtYYQO0A.jpg)

log file
```

### HTMLPrettify diagnostics begin ###
[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"html": {"disallowed_file_patterns": [], "allowed_file_syntaxes": ["html", "xml"], "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"]}, "json": {"disallowed_file_patterns": [], "allowed_file_syntaxes": ["json"], "allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"]}, "js": {"disallowed_file_patterns": [], "allowed_file_syntaxes": ["javascript", "ecma"], "allowed_file_extensions": ["js"]}, "css": {"disallowed_file_patterns": [], "allowed_file_syntaxes": ["css", "sass", "less", "styl", "stylus"], "allowed_file_extensions": ["css", "scss", "sass", "less", "styl", "stylus"]}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/JavaScript/JavaScript.sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: D:\FRONTEND\CLOUDMAILRU\CLOUD\Total\Tools\SublimeText\Data\Packages\HTML-CSS-JS Prettify\05ec5929-5ae9-474c-bf96-bd4a71b92572
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: D:\FRONTEND\STORAGE\WORK\fast-start-setup\gulp-task-libs\stylus-loader.js
[HTMLPrettify] Config extra lookup paths: D:\FRONTEND\CLOUDMAILRU\CLOUD\Total\Tools\SublimeText\Data\Packages\User,D:\FRONTEND\CLOUDMAILRU\CLOUD\Total\Tools\SublimeText\Data\Packages\HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["D:\\FRONTEND\\STORAGE\\WORK\\fast-start-setup\\gulp-task-libs","D:\\FRONTEND\\STORAGE\\WORK\\fast-start-setup","D:\\FRONTEND\\STORAGE\\WORK","D:\\FRONTEND\\STORAGE","D:\\FRONTEND","D:","C:\\Users\\Admin","D:\\FRONTEND\\CLOUDMAILRU\\CLOUD\\Total\\Tools\\SublimeText\\Data\\Packages\\User","D:\\FRONTEND\\CLOUDMAILRU\\CLOUD\\Total\\Tools\\SublimeText\\Data\\Packages\\HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: D:\FRONTEND\CLOUDMAILRU\CLOUD\Total\Tools\SublimeText\Data\Packages\HTML-CSS-JS Prettify\.jsbeautifyrc.defaults.json
[HTMLPrettify] Attempting to parse file: D:\FRONTEND\CLOUDMAILRU\CLOUD\Total\Tools\SublimeText\Data\Packages\User\.jsbeautifyrc
[HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":"","indent_size":1,"indent_with_tabs":true,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":false,"indent_inner_html":false,"indent_scripts":"keep","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true,"brace_style":"collapse","indent_size":2,"indent_with_tabs":false},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"after-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false,"indent_with_tabs":true}},"css":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true,"brace_style":"collapse"},"js":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":1,"indent_with_tabs":true,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"after-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"json":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":1,"indent_with_tabs":true,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"end-expand","keep_array_indentation":false,"unescape_strings":false}}
[HTMLPrettify] Attempting to prettify what seems to be a JS file.
### HTMLPrettify diagnostics end ###
### HTMLPrettify prettified code begin ###
module.exports = (combiner, src, dest, _run, inDevApps, isDevelopment, cssImageLink, cssFontsLink, inPubCss, errorConfig, __cfg) =>
	() => combiner(
		src(`${inDevApps}/stylus/**/connect.styl`),
		_run.if(isDevelopment, _run.sourcemaps.init()),
		_run.stylus(__cfg),
		_run.autoprefixer({ browsers: ['last 5 version'] }),
		_run.if(isDevelopment, _run.sourcemaps.write()),
		_run.urlReplace({ prepend: cssImageLink }),
		_run.urlReplace(cssFontsLink),
		_run.rename('global.css'),
		dest(inPubCss)).on('error',
		_run.notify.onError((err) => errorConfig('Stylus', 'ошибка синтаксиса', err)));
### HTMLPrettify prettified code end ###
```

**Comment by victorporof** [comment] 2018-05-23 08:55
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 08:55 UTC
