### ISSUE TITLE
Node.js was not found in the default path. Please specify the location - in Folders on Sideboards

### ISSUE THREAD

**Issue by webant** [victorporof/Sublime-HTMLPrettify#371] opened 2017-04-03 11:53 UTC
The plugin works only in files opened in Group 1 and Group 2 (on sideboards Group).
Everything is fine here, but ...
The plugin gives errors when formatting a file opened in a FOLDERS (on sideboards Folders).

In other words, two files is open in one Sublime, but the first file works (!) with the plugin, but the second file does not (!).
This is a bug.

How to fix it? Or...
...will this bug be fixed?

My config:
  "node_path": {
    "windows": "C:/Program Files/nodejs/node.exe",
    "linux": "/usr/bin/nodejs",
    "osx": "/usr/local/bin/node"
  },
  "format_on_save": false,
  "format_selection_only": true,
  "print_diagnostics": true
}

**Comment by mermonkey** [comment] 2017-04-09 03:19
Same issue! Didn't realize it was related to Folders...

**Comment by laggingreflex** [comment] 2017-04-14 11:33
That error message might even occur even if you do have your nodejs path set correctly. Like if there's an error parsing the config file - `.jsbeautify` or if an error occurs in the actual beautification process. I've submitted a patch in #346 above that distinguishes these errors, waiting for it to be merged. If you can pull it locally ant test it out please share your results.

**Comment by victorporof** [comment] 2017-06-30 16:03
I cannot reproduce this, but hope that #374 gets rid of this. If it doesn't on the development branch (or master after it gets merged), please reopen.

**Closed** 2017-06-30 16:04 UTC

**Comment by gitressa** [comment] 2021-06-23 21:06
Using Ubuntu (Linux) and got the Node not being found message ... I got a path by typing `whereis node` and inserted the first result (`/usr/bin/node`) as path in the settings file, and it now works.
