### ISSUE TITLE
Can't undo cmd+z on Mac after save

### ISSUE THREAD

**Issue by gioknx** [victorporof/Sublime-HTMLPrettify#367] opened 2017-02-04 21:50 UTC
If I hit cmd+z several times and save, I can't use cmd+shift+z to undo them. Anyone knows why?

The only option I changed in format_on_save and I'm using ST3

**Comment by victorporof** [comment] 2017-07-14 06:59
Is this fixed with the latest release? (2.0.5)

**Comment by victorporof** [comment] 2017-08-02 08:00
Closing this for now as I am unable to reproduce.

**Closed by victorporof** 2017-08-02 08:00 UTC
