### ISSUE TITLE
sublime软件自带格式化出现bug 

### ISSUE THREAD

**Issue by sunshine1208** [victorporof/Sublime-HTMLPrettify#446] opened 2017-07-18 08:16 UTC
Sublime software comes with formatting, appears bug

**Comment by sunshine1208** [comment] 2017-07-18 08:16
Sublime software comes with formatting, appears bug

**Comment by victorporof** [comment] 2017-07-18 08:17
Probably a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/442

**Closed by victorporof** 2017-07-18 08:17 UTC
