### ISSUE TITLE
can't prettify the long html code

### ISSUE THREAD

**Issue by blyk** [victorporof/Sublime-HTMLPrettify#387] opened 2017-07-15 05:12 UTC

**Comment by victorporof** [comment] 2017-07-15 06:33
Does this still happen in version 2.0.6 (released yesterday)?

**Comment by victorporof** [comment] 2017-07-15 06:42
Can you please provide the output in sublime's console? Any specific steps to reproduce this issue? Which Sublime version are you using?

**Comment by victorporof** [comment] 2017-07-15 07:02
I'm making this a duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/380

If this still happens in version 2.0.6, please reopen and provide more information.

**Closed by victorporof** 2017-07-15 07:02 UTC

**Comment by blyk** [comment] 2017-07-16 03:29
Hey, I updated the plugin and it is fixed now :) thanks @victorporof
