### ISSUE TITLE
On every save in css file it inserts blanks lines between rules

### ISSUE THREAD

**Issue by sanaalazmeh** [victorporof/Sublime-HTMLPrettify#521] opened 2018-01-05 03:19 UTC
On every save in css file it inserts blanks lines between rules
in the end, all the file is filled blank lines (100s)
Please fix.
Thanks.

**Comment by minikN** [comment] 2018-01-27 04:06
+1

**Comment by venhryk** [comment] 2018-03-12 09:09
+1

**Comment by victorporof** [comment] 2018-05-23 09:17
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/492

**Closed by victorporof** 2018-05-23 09:17 UTC
