### ISSUE TITLE
crash when pettifying

### ISSUE THREAD

**Issue by boistordu** [victorporof/Sublime-HTMLPrettify#562] opened 2018-05-20 02:56 UTC
[main.1977e1fb.js.zip](https://github.com/victorporof/Sublime-HTMLPrettify/files/2019969/main.1977e1fb.js.zip)
it seems that this files cause some problems

I'm using last stable build of sublime text 3176 under windows 10 pro 17134.48 with node 10.1.0

any advice?

**Comment by victorporof** [comment] 2018-05-23 08:55
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 08:55 UTC
