### ISSUE TITLE
Shortcut key-shift+alt+h（to formatting code）

### ISSUE THREAD

**Issue by AyoDosahard** [victorporof/Sublime-HTMLPrettify#571] opened 2018-05-24 00:56 UTC
error:
'NoneType' object has no attribute 'get'

**Comment by victorporof** [comment] 2018-05-24 06:37
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/516

Can you please post the output from sublime’s console?

**Closed by victorporof** 2018-05-24 06:37 UTC
