### ISSUE TITLE
Not able to prettify code

### ISSUE THREAD

**Issue by reena-netmon** [victorporof/Sublime-HTMLPrettify#606] opened 2018-10-01 04:30 UTC
I am not able to prettify html code in Sublime text. Some run-time error has occurred. Please help asap

**Comment by mauini18** [comment] 2018-10-01 06:03
Happens here too:

`Node.js encountered a runtime error: Unhandled promise rejection Error: Invalid Option Value: The option 'indent_scripts' can contain only the following values:
normal,keep,separate
You passed in: 'seperate'
    at Options._get_selection%\Roamin%\\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\js-beautify\js\src\core\options.js:126:11)
    at Options._get_selection (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\js-beautify\js\src\core\options.js:103:21)
    at new Options (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\js-beautify\js\src\html\options.js:76:30)
    at new Beautifier (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\js-beautify\js\src\html\beautifier.js:238:20)
    at style_html (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\js-beautify\js\src\html\index.js:34:20)
    at Object.style_html (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\js-beautify\js\src\index.js:38:10)
    at _callee$ (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\main.js:111:34)
    at tryCatch (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:114:21)
[HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":1,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":true,"indent_inner_html":true,"indent_scripts":"seperate","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":"\n","selector_separator_newline":true,"indent_size":2},"js":{"brace_style":"end-expand","break_chained_methods":true,"comma_first":false,"e4x":true,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"preserve-newline","space_after_anon_function":true,"space_before_conditional":true,"space_in_empty_paren":true,"space_in_paren":true,"unescape_strings":false,"max_preserve_newlines":2,"unindent_chained_methods":true}},"css":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":1,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":"\n","selector_separator_newline":true},"js":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":2,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"end-expand","break_chained_methods":true,"comma_first":false,"e4x":true,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"preserve-newline","space_after_anon_function":true,"space_before_conditional":true,"space_in_empty_paren":true,"space_in_paren":true,"unescape_strings":false,"unindent_chained_methods":true},"json":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":1,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false}}
[HTMLPrettify] Attempting to prettify what seems to be a HTML file.
### HTMLPrettify diagnostics end ###
### HTMLPrettify prettified code begin ###`

**Comment by mauini18** [comment] 2018-10-01 06:09
> I am not able to prettify html code in Sublime text. Some run-time error has occurred. Please help asap

I had an issue too: 

```
Node.js encountered a runtime error: Unhandled promise rejection Error: Invalid Option Value: The option 'indent_scripts' can contain only the following values:
normal,keep,separate
You passed in: 'seperate'
```

I misspelled it. Search in your console for an error.

**Comment by victorporof** [comment] 2018-10-01 07:17
@reena-netmon can you please post the full output from sublime's console?

**Comment by victorporof** [comment] 2018-10-01 11:29
Likely a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/610

**Closed by victorporof** 2018-10-01 11:29 UTC
