### ISSUE TITLE
is error

### ISSUE THREAD

**Issue by godnes001** [victorporof/Sublime-HTMLPrettify#447] opened 2017-07-18 08:25 UTC
![qq 20170718162448](https://user-images.githubusercontent.com/30073668/28307497-afe80772-6bd5-11e7-9560-288511108e5c.png)

**Comment by victorporof** [comment] 2017-07-18 12:03
Duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/442

**Closed by victorporof** 2017-07-18 12:03 UTC
