### ISSUE TITLE
Node.js encountered a runtime error: Unhandled promise rejection TypeError: Object.entries is not a function

### ISSUE THREAD

**Issue by bountyvcs** [victorporof/Sublime-HTMLPrettify#611] opened 2018-10-01 13:41 UTC
Hi Victor, I've been using HTMLPrettify on Mac for years and wanted to say thanks first of all.

I just tried to use it today and got this message:

A runtime error was encountered in the prettifier. See the console output for more information. Do you wish to file a bug?

Here is the output from the console:

Node.js encountered a runtime error: Unhandled promise rejection TypeError: Object.entries is not a function
    at extendJsbeautifyConfig (/Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/utils/configUtils.js:88:21)
    at _callee2$ (/Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/utils/configUtils.js:145:47)
    at tryCatch (/Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/regenerator-runtime/runtime.js:288:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

### HTMLPrettify diagnostics begin ###
[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"js": {"allowed_file_syntaxes": ["javascript", "ecma", "react", "babel"], "allowed_file_extensions": ["js", "jsx"], "disallowed_file_patterns": []}, "json": {"allowed_file_syntaxes": ["json"], "allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"], "disallowed_file_patterns": []}, "css": {"allowed_file_syntaxes": ["css", "sass", "less"], "allowed_file_extensions": ["css", "scss", "sass", "less"], "disallowed_file_patterns": []}, "html": {"allowed_file_syntaxes": ["html", "xml", "vue"], "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "vue"], "disallowed_file_patterns": []}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/HTML/HTML.sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: /Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/13db18ac-82c9-4318-8dff-e4fd70caef09
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: /Users/Ben/Sites/work/client/2018_10_01-creative/2018_10_01-creative.html
[HTMLPrettify] Config extra lookup paths: /Users/Ben/Library/Application Support/Sublime Text 3/Packages/User,/Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["/Users/Ben/Sites/work/client/2018_10_01-creative","/Users/Ben/Sites/work/client","/Users/Ben/Sites/work","/Users/Ben/Sites","/Users/Ben","/Users","/Users/Ben","/Users/Ben/Library/Application Support/Sublime Text 3/Packages/User","/Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: /Users/Ben/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc.defaults.json
[HTMLPrettify] Attempting to parse file: /Users/Ben/Library/Application Support/Sublime Text 3/Packages/User/.jsbeautifyrc

I've done some searching but can't find a solution on my own - I also looked at previous issues in this repo but couldn't see anything that I thought was similar.

Any help you could provide would be greatly appreciated.

Cheers!

Ben

**Comment by gfdesign** [comment] 2018-10-01 13:54
I have same problem using using PC/Win10
I've been using this package for several months and it worked fine, until now.
I also removed it and install it again but error still continues.
Looking forward any advance in this :)
Best regards

**Comment by bountyvcs** [comment] 2018-10-01 14:00
I have also tried removing and re-installing to no avail.

Ta

**Comment by victorporof** [comment] 2018-10-01 19:14
Thanks for the detailed reports! Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/610

Try updating node; real fix incoming.

**Closed by victorporof** 2018-10-01 19:14 UTC
