### ISSUE TITLE
Node JS runtime error (node:6967)

### ISSUE THREAD

**Issue by wheatbrad** [victorporof/Sublime-HTMLPrettify#574] opened 2018-05-25 01:25 UTC
Cryptic Node JS runtime error when prettifying small HTML file.

`Node.js encountered a runtime error: (node:6967)`

Sublime Text -v 3.1.1
Node -v 10.1.0

Oddly enough, after encountering the runtime error, HTMLPrettify will prettify the markup and print to the Sublime Text console.

**Comment by victorporof** [comment] 2018-06-15 05:03
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/576

**Closed by victorporof** 2018-06-15 05:03 UTC
