### ISSUE TITLE
can't use to format code

### ISSUE THREAD

**Issue by Stupidleilei** [victorporof/Sublime-HTMLPrettify#550] opened 2018-05-03 07:23 UTC
![image](https://user-images.githubusercontent.com/5979462/39564170-b4bad97a-4ee5-11e8-8cd0-13f33a6b6711.png)

After the upgrade, it doesn't work

0.0

**Comment by victorporof** [comment] 2018-05-23 08:56
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 08:56 UTC
