### ISSUE TITLE
Node.js encountered a runtime error: (node:4904) ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by benobee** [victorporof/Sublime-HTMLPrettify#561] opened 2018-05-18 19:56 UTC
Node.js encountered a runtime error: (node:4904) ExperimentalWarning: The fs.promises API is experimental

### HTMLPrettify diagnostics begin ###
[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"json": {"allowed_file_syntaxes": ["json"], "disallowed_file_patterns": [], "allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"]}, "html": {"allowed_file_syntaxes": ["html", "xml"], "disallowed_file_patterns": [], "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"]}, "css": {"allowed_file_syntaxes": ["css", "sass", "less"], "disallowed_file_patterns": [], "allowed_file_extensions": ["css", "scss", "sass", "less"]}, "js": {"allowed_file_syntaxes": ["javascript", "ecma"], "disallowed_file_patterns": [], "allowed_file_extensions": ["js"]}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/HTML/HTML.sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: /Users/benobee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/fe4a76a9-2ae2-454e-9af3-25f921f9d746
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: /Users/benobee/dev/boich/test/index.html
[HTMLPrettify] Config extra lookup paths: /Users/benobee/Library/Application Support/Sublime Text 3/Packages/User,/Users/benobee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["/Users/benobee/dev/boich/test","/Users/benobee/dev/boich","/Users/benobee/dev","/Users/benobee","/Users","/Users/benobee","/Users/benobee/Library/Application Support/Sublime Text 3/Packages/User","/Users/benobee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: /Users/benobee/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc.defaults.json
[HTMLPrettify] Attempting to parse file: /Users/benobee/Library/Application Support/Sublime Text 3/Packages/User/.jsbeautifyrc
[HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":false,"indent_inner_html":false,"indent_scripts":"keep","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false}},"css":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"json":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false}}
[HTMLPrettify] Attempting to prettify what seems to be a HTML file.
### HTMLPrettify prettified code begin ###
<!DOCTYPE html>
<!html>

<body class="site">
  <div class="site-wrapper">
    <div class="site">
      <div class="header">
        <div class="nav-wrapper">
          <div class="nav">
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>
### HTMLPrettify prettified code end ###

**Comment by Exeteres** [comment] 2018-05-22 05:40
This problem occurs after upgrading to node 10. I just downloaded and unzipped node 8 into a separate folder and pointed to the path to node (.exe)
Solution for linux x64:
`cd /tmp`
`wget https://nodejs.org/dist/v8.11.2/node-v8.11.2-linux-x64.tar.xz`
`tar -xvf node-v8.11.2-linux-x64.tar.xz -C ~/`
And specify the path to node(in HTMLPrettify.sublime-settings):
`"node_path":    
   {
         ...
        "linux": "/home/<username>/node-v8.11.2-linux-x64/bin/node"
         ...
    }`

**Comment by victorporof** [comment] 2018-05-23 09:28
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 09:28 UTC
