### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by asiftyro** [victorporof/Sublime-HTMLPrettify#573] opened 2018-05-24 11:31 UTC
Getting following error after updating sublime to v3.1.1 build 3176:
"A runtime error was encountered in the prettifier. See the console output for more information. Do you wish to file a bug?"

**Comment by asiftyro** [comment] 2018-05-24 11:42
Console Output

[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"html": {"disallowed_file_patterns": [], "allowed_file_syntaxes": ["html", "xml"], "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"]}, "json": {"disallowed_file_patterns": [], "allowed_file_syntaxes": ["json"], "allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"]}, "js": {"disallowed_file_patterns": [], "allowed_file_syntaxes": ["javascript", "ecma"], "allowed_file_extensions": ["js"]}, "css": {"disallowed_file_patterns": [], "allowed_file_syntaxes": ["css", "sass", "less"], "allowed_file_extensions": ["css", "scss", "sass", "less"]}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/Babel/JavaScript (Babel).sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: /Users/asif/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/6d104f71-95a3-45b8-aa87-38bdde025358
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: /Users/asif/Dropbox/stan/app.js
[HTMLPrettify] Config extra lookup paths: /Users/asif/Library/Application Support/Sublime Text 3/Packages/User,/Users/asif/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["/Users/asif/Dropbox/stan","/Users/asif/Dropbox","/Users/asif","/Users","/Users/asif","/Users/asif/Library/Application Support/Sublime Text 3/Packages/User","/Users/asif/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: /Users/asif/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc.defaults.json
[HTMLPrettify] Attempting to parse file: /Users/asif/Library/Application Support/Sublime Text 3/Packages/User/.jsbeautifyrc
[HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":2,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":true,"indent_inner_html":true,"indent_scripts":"keep","unformatted":["{{>","{{","{{#","{{/","}}","a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false}},"css":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":2,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":2,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"json":{"end_with_newline":true,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":2,"indent_with_tabs":false,"max_preserve_newlines":2,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false}}
[HTMLPrettify] Attempting to prettify what seems to be a JS file.

**Comment by victorporof** [comment] 2018-05-24 11:56
Likely a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553
Please update and let me know if it still happens.

**Closed by victorporof** 2018-05-24 11:56 UTC
