### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by matomegu** [victorporof/Sublime-HTMLPrettify#684] opened 2019-07-31 21:20 UTC
A runtime error was encountered in the prettifier. 
See the console output for more information. Do you wish to file a bug?

The console error is like this:
Node.js encountered a runtime error: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.62.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found

My OS version is mac10.14.3
Node version is v11.13.0

**Comment by rhdez** [comment] 2019-08-14 23:25
Same issue here.  It just started happening to me about a week ago. :(

**Comment by liunan-lynn** [comment] 2019-10-30 07:13
`brew upgrade node` works for me
Node version v12.12.0 works

**Comment by raineorshine** [comment] 2020-03-22 16:26
`brew update && brew upgrade` and restart Sublime fixed it for me.

Similar to https://github.com/facebook/react-native/issues/18760

**Comment by raineorshine** [comment] 2020-03-22 16:27
Duplicate of #601

**Closed as completed** 2020-03-23 10:42 UTC
