### ISSUE TITLE
new default collapse-preserve-inline is probably not ideal for json.

### ISSUE THREAD

**Issue by frame** [victorporof/Sublime-HTMLPrettify#287] opened 2016-02-22 13:13 UTC
The recently introduced setting brace_style "collapse-preserve-inline" is in my opinion great for .js, but not so much for .json.

Is there a way to either exclude .json from this rule of maybe define different rules per extension?

```
{
	"js": {
		"allowed_file_extensions": ["js"],
		"brace_style": "collapse-preserve-inline"
	},
	"js_alternative": {
		"allowed_file_extensions": ["json", "jshintrc", "jsbeautifyrc"],
		"brace_style": "collapse"
	}
}
```

Thanks for your time!

**Comment by evenfrost** [comment] 2016-03-17 13:28
Same here. The issue I'm getting right now with `collapse-preserve-inline` option is JSON not being prettified if is initially inline.

**Comment by victorporof** [comment] 2016-03-18 13:52
It'd be really nice if we could specify different config files for js vs. json.

**Comment by victorporof** [comment] 2016-04-08 05:42
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/148

**Closed by victorporof** 2016-04-08 05:42 UTC
