### ISSUE TITLE
not working with latest version of sublime text - Sublime Text 3 (Build 3143)

### ISSUE THREAD

**Issue by shamseerahammedm** [victorporof/Sublime-HTMLPrettify#488] opened 2017-09-23 14:18 UTC

**Comment by h13579** [comment] 2017-10-09 23:30
It works for me. After installing through **Package Control**, i renamed the folder to be 'Sublime-HTMLPrettify'.
What errors do you get?

**Comment by yisenliu** [comment] 2017-10-11 09:01
Same here. It's not working with **ST3 build 3143** when I want to prettify **.js** file and there is no errors showed. Even reinstalling this package, it's still not working.

**Comment by victorporof** [comment] 2018-05-23 09:01
Possibly a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/567 which I'm pushing a fix for today.

Please reopen with more details if not the case.

**Closed by victorporof** 2018-05-23 09:01 UTC
