### ISSUE TITLE
Node.js was not found in the default path. Please specify the location - mac os x 10.11

### ISSUE THREAD

**Issue by LeonardoGentile** [victorporof/Sublime-HTMLPrettify#338] opened 2016-09-14 09:05 UTC
This issue is exactly like #166, except that it is still reproducible.
I've tried to comment on #166 but it was not re-opened, so just for visibility I'm reporting the problem here:

I'm on Mac 10.11.6 and I'm using nvm.

My settings for the node path are:

```
 "node_path": {
    "windows": "C:/Program Files/nodejs/node.exe",
    "linux": "/usr/bin/nodejs",
    "osx": "/Users/foo/.nvm/versions/node/v6.3.1/bin/node"   // Result of "which node"
  }
```

but anytime I hit the shortcuts for launching the command Sublime complains

```
Node.js was not found in the default path. Please specify the location.
```

Node works fine for me from the command line

**Comment by oivva** [comment] 2016-09-16 14:15
The same on Windows

**Comment by VocrsZ** [comment] 2016-09-30 17:18
The same

**Comment by bmarkovic** [comment] 2016-10-01 09:52
Same behaviour on windows, if I place any of results of `where node` in the settings file (replacing backslashes with slashes) the command still doesn't work.

**Comment by laggingreflex** [comment] 2016-10-11 13:14
@bmarkovic You seem to be right. related: #345

**Comment by duranmg** [comment] 2016-11-18 17:54
has there ever been  a fix for this?  I'm getting the issue on Windows.

**Comment by borderNull** [comment] 2016-11-23 23:11
Hi ***duranmg***  you need to specify location from this type  ```   "windows": "C/:Program Files/nodejs/node.exe"```  to this  ```"windows": "C:/Program Files/nodejs/node.exe"```  ,  in other words just change  ```/``` and ```:``` their places,  cause in my case incorrect type was set by default , but route was correct , i just changed that , and  now all working.

**Comment by laggingreflex** [comment] 2016-11-24 01:25
The problem is that that error message might even occur even if you do have your nodejs path set correctly. Like if there's an error parsing the config file - `.jsbeautify` or if an error occurs in the actual beautification process. I've submitted a patch in #346 above, waiting for it to be merged. If you can pull it locally ant test it out please share your results.

**Comment by duranmg** [comment] 2016-12-14 19:57
That's not the problem.  My config file is alreayd like that:

`node_path": {
    "windows": "C:/Program Files/nodejs/node.exe",
    "linux": "/usr/bin/nodejs",
    "osx": "/usr/local/bin/node"
  },`

**Comment by victorporof** [comment] 2017-06-27 17:41
Better error handling comes with #374

**Closed by victorporof** 2017-06-27 17:41 UTC
