### ISSUE TITLE
can not use prettyify

### ISSUE THREAD

**Issue by EchoSpot** [victorporof/Sublime-HTMLPrettify#547] opened 2018-04-25 02:16 UTC
I have set node_path correctly,but still can not use html css s prettyify,I have no idea about this question .sorry. my English is poor

**Comment by victorporof** [comment] 2018-05-23 08:57
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 08:57 UTC
