### ISSUE TITLE
Cannot read property 'disallowed_file_patterns' of undefined

### ISSUE THREAD

**Issue by KoteKotlyarov** [victorporof/Sublime-HTMLPrettify#460] opened 2017-07-22 11:12 UTC
1. Open JS file
2. Do a clean install\reinstall of package
3. Press CTRL + SHIFT + H or "Package Controll -> Prettify" to pretiffy file
4. Got "Runtime error in package"
5. See Sublime console:

`Node.js encountered a runtime error: Unhandled promise rejection TypeError: Cannot read property 'disallowed_file_patterns' of undefined
    at isDisallowedFilePattern (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\fileUtils.js:38:80)
    at isCSS (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\fileUtils.js:135:7)
    at _callee$ (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\main.js:85:38)
    at tryCatch (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13

### HTMLPrettify diagnostics begin ###
[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"html": {"allowed_file_syntaxes": [], "allowed_file_extensions": [], "disallowed_file_patterns": []}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/JavaScript/JavaScript.sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\7feec724-391c-4175-818b-9980d362335a
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: D:\Github\rs-report-service\client\modules\product-release\product-release\vm.js
[HTMLPrettify] Config extra lookup paths: C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\User,C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["D:\\Github\\rs-report-service\\client\\modules\\product-release\\product-release","D:\\Github\\rs-report-service\\client\\modules\\product-release","D:\\Github\\rs-report-service\\client\\modules","D:\\Github\\rs-report-service\\client","D:\\Github\\rs-report-service","D:\\Github","D:","C:\\Users\\username","C:\\Users\\username\\AppData\\Roaming\\Sublime Text 3\\Packages\\User","C:\\Users\\username\\AppData\\Roaming\\Sublime Text 3\\Packages\\HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\.jsbeautifyrc.defaults.json
[HTMLPrettify] Attempting to parse file: C:\Users\username\.jsbeautifyrc
[HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":false,"indent_inner_html":false,"indent_scripts":"keep","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"allowed_file_extensions":[],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false}},"css":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"json":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false}}`

About a week ago this package removes all my preferences. "Ok" - said I and edit default one.
Today I wanted to disable pretiffy HTML files, openned "Plugin options", and remove **html** section from **global_file_rules** block. Tried to save and it fails... Starting from that point, package fails.

I tried to remove it, looked at folder `c:\Users\useraname\AppData\Roaming\Sublime Text 3\Packages\` and dont see any "HTML-CSS-JS Prettify" folder, reinstall package and nothing...

Then I removed it again, created my own **.jsbeautifyrc** file in project folder and it fails again...

What have I done ?

**Comment by victorporof** [comment] 2017-07-22 14:22
Duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/454

**Closed by victorporof** 2017-07-22 14:22 UTC
