### ISSUE TITLE
Cannot read property 'disallowed_file_patterns' of undefined

### ISSUE THREAD

**Issue by wzup** [victorporof/Sublime-HTMLPrettify#465] opened 2017-07-28 15:55 UTC
```
Node.js encountered a runtime error: Unhandled promise rejection TypeError: Cannot read property 'disallowed_file_patterns' of undefined
    at isDisallowedFilePattern (C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\fileUtils.js:38:80)
    at isCSS (C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\fileUtils.js:135:7)
    at _callee$ (C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\main.js:85:38)
    at tryCatch (C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
    at run (C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\core-js\library\modules\es6.promise.js:87:22)
    at C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\core-js\library\modules\es6.promise.js:100:28

### HTMLPrettify diagnostics begin ###
[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"html": {"allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "dust"]}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/JavaScript/JSON.sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\b74a2cfb-7afe-44e9-a73d-678c96993f74
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\User\HTMLPrettify.sublime-settings
[HTMLPrettify] Config extra lookup paths: C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\User,C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\User","C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages","C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3","C:\\Users\\user\\AppData\\Roaming","C:\\Users\\user\\AppData","C:\\Users\\user","C:\\Users","C:","C:\\Users\\user","C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\User","C:\\Users\\user\\AppData\\Roaming\\Sublime Text 3\\Packages\\HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\.jsbeautifyrc.defaults.json
[HTMLPrettify] Attempting to parse file: C:\Users\user\AppData\Roaming\Sublime Text 3\Packages\User\.jsbeautifyrc
[HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":false,"indent_inner_html":false,"indent_scripts":"keep","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"brace_style":"expand"},"css":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true,"brace_style":"expand"},"js":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"json":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false}}
```

**Comment by victorporof** [comment] 2017-07-28 17:50
Duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/454

**Closed by victorporof** 2017-07-28 17:50 UTC

**Comment by wzup** [comment] 2017-07-29 07:07
Yes, it solved the issue.
