### ISSUE TITLE
Runtime error when using HTML prettify

### ISSUE THREAD

**Issue by Tdude** [victorporof/Sublime-HTMLPrettify#515] opened 2017-12-05 14:24 UTC
I pasted in some html in a new tab (had 8 previously open tabs with not too much content, except for one w 8000 lines json).

**Comment by victorporof** [comment] 2018-05-23 09:13
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/487

**Closed by victorporof** 2018-05-23 09:13 UTC
