### ISSUE TITLE
A runtime error was encountered in the prettifier

### ISSUE THREAD

**Issue by clay-f** [victorporof/Sublime-HTMLPrettify#553] opened 2018-05-11 14:24 UTC
node -v: 10.1.0
sublime text version: 3170
os version: mac os 10.13

        Node.js encountered a runtime error: (node:6051) ExperimentalWarning: The fs.promises API is experimental

        ### HTMLPrettify diagnostics begin ###
        [HTMLPrettify] Using editor text temp file: True
        [HTMLPrettify] Global file rules: {"json": {"allowed_file_syntaxes": ["json"], "allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"], "disallowed_file_patterns": []}, "html": {"allowed_file_syntaxes": ["html", "xml"], "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"], "disallowed_file_patterns": []}, "css": {"allowed_file_syntaxes": ["css", "sass", "less"], "allowed_file_extensions": ["css", "scss", "sass", "less"], "disallowed_file_patterns": []}, "js": {"allowed_file_syntaxes": ["javascript", "ecma"], "allowed_file_extensions": ["js"], "disallowed_file_patterns": []}}
        [HTMLPrettify] Respecting .editorconfig files: True
        [HTMLPrettify] Editor file syntax: Packages/HTML/HTML.sublime-syntax
        [HTMLPrettify] Editor indent size: ?
        [HTMLPrettify] Editor indent with tabs: ?
        [HTMLPrettify] Editor text file path: /Users/f/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/1c95cf27-9013-49ab-a719-a7a44d1aaeff
        [HTMLPrettify] Editor text file contents: null
        [HTMLPrettify] Original file path: /Users/f/Documents/develop/workspace/animate-flexslider/index.html
        [HTMLPrettify] Config extra lookup paths: /Users/f/Library/Application Support/Sublime Text 3/Packages/User,/Users/f/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify
        [HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["/Users/f/Documents/develop/workspace/animate-flexslider","/Users/f/Documents/develop/workspace","/Users/f/Documents/develop","/Users/f/Documents","/Users/f","/Users","/Users/f","/Users/f/Library/Application Support/Sublime Text 3/Packages/User","/Users/f/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify"]
        [HTMLPrettify] Attempting to parse file: /Users/f/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc.defaults.json
        [HTMLPrettify] Attempting to parse file: /Users/f/Library/Application Support/Sublime Text 3/Packages/User/.jsbeautifyrc
        [HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":false,"indent_inner_html":false,"indent_scripts":"keep","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false}},"css":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"json":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false}}
        [HTMLPrettify] Attempting to prettify what seems to be a HTML file.
        ### HTMLPrettify diagnostics end ###
        ### HTMLPrettify prettified code begin ###
        <!DOCTYPE html>
        <html>

        <head>
        </head>

        <body>
            <ul>
                <li id="marked">
                    <p>one</p>
                    <p>two</p>
                    <p>three</p>
                    <p>four</p>
                    <p>five</p>
                </li>
                <li>
                    <p>1</p>
                    <p>2</p>
                    <p>3</p>
                    <p>4</p>
                    <p>5</p>
                </li>
            </ul>
            <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        </body>

        </html>
        ### HTMLPrettify prettified code end ###

        reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
        reloading settings Packages/HTML-CSS-JS Prettify/HTMLPrettify.sublime-settings
        Node.js encountered a runtime error: (node:6057) ExperimentalWarning: The fs.promises API is experimental

        ### HTMLPrettify diagnostics begin ###
        [HTMLPrettify] Using editor text temp file: True
        [HTMLPrettify] Global file rules: {"json": {"allowed_file_syntaxes": ["json"], "allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"], "disallowed_file_patterns": []}, "html": {"allowed_file_syntaxes": ["html", "xml"], "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"], "disallowed_file_patterns": []}, "css": {"allowed_file_syntaxes": ["css", "sass", "less"], "allowed_file_extensions": ["css", "scss", "sass", "less"], "disallowed_file_patterns": []}, "js": {"allowed_file_syntaxes": ["javascript", "ecma"], "allowed_file_extensions": ["js"], "disallowed_file_patterns": []}}
        [HTMLPrettify] Respecting .editorconfig files: True
        [HTMLPrettify] Editor file syntax: Packages/HTML/HTML.sublime-syntax
        [HTMLPrettify] Editor indent size: ?
        [HTMLPrettify] Editor indent with tabs: ?
        [HTMLPrettify] Editor text file path: /Users/f/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/afdb911d-c5a9-4501-aa82-b53c0c6a78f1
        [HTMLPrettify] Editor text file contents: null
        [HTMLPrettify] Original file path: /Users/f/Documents/develop/workspace/animate-flexslider/index.html
        [HTMLPrettify] Config extra lookup paths: /Users/f/Library/Application Support/Sublime Text 3/Packages/User,/Users/f/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify
        [HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["/Users/f/Documents/develop/workspace/animate-flexslider","/Users/f/Documents/develop/workspace","/Users/f/Documents/develop","/Users/f/Documents","/Users/f","/Users","/Users/f","/Users/f/Library/Application Support/Sublime Text 3/Packages/User","/Users/f/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify"]
        [HTMLPrettify] Attempting to parse file: /Users/f/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc.defaults.json
        [HTMLPrettify] Attempting to parse file: /Users/f/Library/Application Support/Sublime Text 3/Packages/User/.jsbeautifyrc
        [HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":false,"indent_inner_html":false,"indent_scripts":"keep","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false}},"css":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"json":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false}}
        [HTMLPrettify] Attempting to prettify what seems to be a HTML file.
        ### HTMLPrettify diagnostics end ###
        ### HTMLPrettify prettified code begin ###
        <!DOCTYPE html>
        <html>

        <head>
        </head>

        <body>
            <ul>
                <li id="marked">
                    <p>one</p>
                    <p>two</p>
                    <p>three</p>
                    <p>four</p>
                    <p>five</p>
                </li>
                <li>
                    <p>1</p>
                    <p>2</p>
                    <p>3</p>
                    <p>4</p>
                    <p>5</p>
                </li>
            </ul>
            <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        </body>

        </html>

**Comment by MormonJesus69420** [comment] 2018-05-16 13:57
Same here, running on Arch Linux with Node v10.1.0
 
```
Node.js encountered a runtime error: (node:21477) ExperimentalWarning: The fs.promises API is experimental

### HTMLPrettify diagnostics begin ###
[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"json": {"allowed_file_syntaxes": ["json"], "disallowed_file_patterns": [], "allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"]}, "html": {"allowed_file_syntaxes": ["html", "xml"], "disallowed_file_patterns": [], "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"]}, "css": {"allowed_file_syntaxes": ["css", "sass", "less"], "disallowed_file_patterns": [], "allowed_file_extensions": ["css", "scss", "sass", "less"]}, "js": {"allowed_file_syntaxes": ["javascript", "ecma"], "disallowed_file_patterns": [], "allowed_file_extensions": ["js"]}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/HTML/HTML.sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: /home/mormonjz/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/3dfc0947-1350-4bc2-891a-8787e93fc774
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: /home/mormonjz/Desktop/test.html
[HTMLPrettify] Config extra lookup paths: /home/mormonjz/.config/sublime-text-3/Packages/User,/home/mormonjz/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["/home/mormonjz/Desktop","/home/mormonjz","/home","/home/mormonjz","/home/mormonjz/.config/sublime-text-3/Packages/User","/home/mormonjz/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: /home/mormonjz/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc.defaults.json
[HTMLPrettify] Computed prettify options: {"html":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"indent_handlebars":false,"indent_inner_html":false,"indent_scripts":"keep","unformatted":["a","span","img","code","pre","sub","sup","em","strong","b","i","u","strike","big","small","pre","h1","h2","h3","h4","h5","h6"],"css":{"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false}},"css":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"newline_between_rules":true,"selector_separator":" ","selector_separator_newline":true},"js":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"collapse-preserve-inline","break_chained_methods":false,"comma_first":false,"e4x":false,"jslint_happy":false,"keep_array_indentation":false,"keep_function_indentation":false,"operator_position":"before-newline","space_after_anon_function":false,"space_before_conditional":true,"space_in_empty_paren":false,"space_in_paren":false,"unescape_strings":false},"json":{"end_with_newline":false,"eol":"\n","indent_level":0,"indent_char":" ","indent_size":4,"indent_with_tabs":false,"max_preserve_newlines":0,"preserve_newlines":true,"wrap_line_length":0,"brace_style":"expand","keep_array_indentation":false,"unescape_strings":false}}
[HTMLPrettify] Attempting to prettify what seems to be a HTML file.
### HTMLPrettify diagnostics end ###
### HTMLPrettify prettified code begin ###
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>
    <p>Bah</p>
</body>

</html>
### HTMLPrettify prettified code end ###
```

**Comment by panda912** [comment] 2018-05-17 05:40
I also have the same problem.

**Comment by andreydro** [comment] 2018-05-21 12:47
The same issue
The same environment
  node -v: 10.1.0
  sublime text version: 3170
  os version: mac os 10.13

**Comment by victorporof** [comment] 2018-05-22 19:23
Pushing a new version tomorrow! Thanks y’all for your patience!

In the meantime, I think downgrading your node version (if posible) would make this go away.

**Comment by niladam** [comment] 2018-05-23 07:06
@victorporof it would be great if you could also have a develop or beta branch we could pull from. For me, downgrading node isn't an option and i assume for most of us is that's the same case..

I'm looking forward towards your push :) 👍

**Comment by victorporof** [comment] 2018-05-23 09:28
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Comment by victorporof** [comment] 2018-05-23 09:30
Oops, duped to itself.

**Comment by niladam** [comment] 2018-05-23 09:30
@victorporof hah! I was just about to tell you that!:P

**Comment by victorporof** [comment] 2018-05-23 09:48
Fixed in https://github.com/victorporof/Sublime-HTMLPrettify/commit/a8a184818884e8bda81f76ed8a55b513b3bbbd82

Please update your plugin and let me know if everything works as expected.
Tested locally using node v10.1.0

**Closed by victorporof** 2018-05-23 09:48 UTC

**Comment by niladam** [comment] 2018-05-23 09:59
@victorporof you also need to make a release so that the plugin gets updated via Packagecontrol too :)

**Comment by victorporof** [comment] 2018-05-23 10:11
Are you sure about that? Is this a new development with Sublime?
In the past, whatever was HEAD on the master branch was what the editor used to update the plugin.

**Comment by MormonJesus69420** [comment] 2018-05-23 10:14
Well, it hasn't updated for me so far. So I imagine that @niladam is right.

**Comment by victorporof** [comment] 2018-05-23 10:16
Perhaps! I haven't followed Sublime's latest changes in a while!
New release at https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.1.4

In the meantime, you can update manually: https://github.com/victorporof/Sublime-HTMLPrettify#manually Make sure you remove the package control installation if you do that, since Sublime has two different plugin installation directories.

**Comment by niladam** [comment] 2018-05-23 10:16
I can confirm that manually editing/changing the file fixes the issue, but i was unable to upgrade via packagecontrol.

**Comment by niladam** [comment] 2018-05-23 10:17
@victorporof according the packagecontrol plugin's page the last modification happened 10 months ago. So i'm guessing, it's probably using some sort of cache ?

**Comment by niladam** [comment] 2018-05-23 10:18
@victorporof also, as per their [Step 4](https://packagecontrol.io/docs/submitting_a_package#Step_4) you basically need to use SEMVER, and probably also update your package.json too :)

**Comment by MormonJesus69420** [comment] 2018-05-23 11:38
Works now
