### ISSUE TITLE
HTML/CSS/JS  Prettify  error

### ISSUE THREAD

**Issue by wangxiaotian** [victorporof/Sublime-HTMLPrettify#390] opened 2017-07-15 07:06 UTC
in blade template condition , use HTML/CSS/JS Prettify  html code has a error

**Comment by victorporof** [comment] 2017-07-15 07:10
Please provide with more information. What is your sublime version? What's the output in sublime's console? Does the plugin work with other files? What's the plugin version (look inside the package.json in the plugin's installation directory)

**Comment by victorporof** [comment] 2017-07-15 08:16
Marking as a duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/386

Please reopen with more information if this is not the case.

**Closed by victorporof** 2017-07-15 08:16 UTC

**Comment by victorporof** [comment] 2017-07-17 06:36
Updating to the latest version https://github.com/victorporof/Sublime-HTMLPrettify/releases will help you better figure out what's going wrong.

I'd still appreciate some meaningful bug report, but if everything else still goes wrong, you can revert to the latest stable version 1.0.0
