### ISSUE TITLE
an unhandled error was encountered while prettifying 

### ISSUE THREAD

**Issue by NolaJun** [victorporof/Sublime-HTMLPrettify#450] opened 2017-07-18 09:12 UTC
I hit down 'ctrl+ shift + h', a popup is display and the message is 'an unhandled error was encountered while prettifying ', how could i do ?

**Comment by victorporof** [comment] 2017-07-18 12:03
Duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/442

**Closed by victorporof** 2017-07-18 12:03 UTC
