### ISSUE TITLE
Not able to prettify the code

### ISSUE THREAD

**Issue by 4791manish** [victorporof/Sublime-HTMLPrettify#461] opened 2017-07-24 17:48 UTC
I am getting an error while pettifying the code as" An unhandled error encountered while prettifying,please report the bug with this link.How can I fix this?Reply asap

**Comment by victorporof** [comment] 2017-07-24 19:51
Please post the output in sublime's console.

**Comment by gummiforweb** [comment] 2017-07-28 05:03
I'm also unable to prettify my code all the sudden, it used to work before.

Here's my sample file (PHP), .jsbeautifyrc and console error
https://gist.github.com/gummiforweb/481a287eda0af72a117fe6c564632a0e.js

Thanks.  :)

**Comment by victorporof** [comment] 2017-08-02 07:36
@gummiforweb This is a duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/454

**Closed by victorporof** 2017-08-02 07:36 UTC

**Comment by victorporof** [comment] 2017-08-02 07:37
@gummiforweb `global_file_rules` needs to contain all necessary keys, so `html`, `css`, `js`, `json`.
