### ISSUE TITLE
Node path not set

### ISSUE THREAD

**Issue by Dalton123** [victorporof/Sublime-HTMLPrettify#464] opened 2017-07-27 16:46 UTC

**Comment by cforelle** [comment] 2017-08-01 14:09
I also have this problem, despite the path actually appearing to be set correctly. This is a relatively recent development. 
![image](https://user-images.githubusercontent.com/10046979/28829340-48e27ae8-76cb-11e7-9247-0784f80b3039.png)

**Comment by victorporof** [comment] 2017-08-02 07:36
What is the output in sublime's console?

**Comment by cforelle** [comment] 2017-08-02 09:43
`Using node.js path on 'windows': C:/Program Files/nodejs/node.exe`
`Unexpected error(<class 'OSError'>): [WinError 6] The handle is invalid`

**Comment by victorporof** [comment] 2017-08-02 11:52
Ok, so this is a duplicate of #455

**Closed by victorporof** 2017-08-02 11:52 UTC
