### ISSUE TITLE
Can't Use Prettify

### ISSUE THREAD

**Issue by ensustudio** [victorporof/Sublime-HTMLPrettify#389] opened 2017-07-15 06:40 UTC
Can't use Prettify on SublimeText 3 to Prettify HTML CSS or JS

**Comment by victorporof** [comment] 2017-07-15 06:46
Please provide more information. What version is the plugin (you can see that in package.json in the plugin's folder)? What node version is installed on your machine? Is there any output in sublime's console?

**Comment by vinaynb** [comment] 2017-07-15 06:47
I think this is duplicate of #386 #387 
@victorporof the latest release has made this plugin unusable for most of users. Please look into the logs i posted in #386 if that helps.

**Comment by victorporof** [comment] 2017-07-15 06:52
@vinaynb I doubt it's most users :) We've been using a development branch for quite a while and people weren't really complaining that much.

However, it does seem that there's a minority for which this plugin has stopped working, and I'm looking into it.

Closing as duplicate of #386

**Closed by victorporof** 2017-07-15 06:52 UTC

**Comment by ensustudio** [comment] 2017-07-15 06:53
Well....The plugin version is 2.0.6

**Comment by vinaynb** [comment] 2017-07-15 06:53
@victorporof yes you definitely know better than me. Let me know if i can help in any way to fix this issue !

**Comment by victorporof** [comment] 2017-07-15 06:55
@ensustudio Just in case, can you provide the information requested in my previous comment https://github.com/victorporof/Sublime-HTMLPrettify/issues/389#issuecomment-315514680 ?

**Comment by ensustudio** [comment] 2017-07-15 07:11
Node.js version is 6.9.2.0
Other plugin:
![image](https://user-images.githubusercontent.com/14163704/28237354-d63639c0-696f-11e7-8331-849dad2fe609.png)

**Comment by victorporof** [comment] 2017-07-15 07:13
@ensustudio Is the node path specified in your plugin's config file the same path to the 6.9.2.0 version?

**Comment by ensustudio** [comment] 2017-07-15 07:24
OK~ I think you just found my issue's answer that path is wrong. I have change it, and the plugin works.
Thanks @victorporof  and sorry about I didn't check the path first.

Thank You for your help. 👍
