### ISSUE TITLE
A runtime error was encountered in the prettifier. see the console output for more information

### ISSUE THREAD

**Issue by widewaystudio** [victorporof/Sublime-HTMLPrettify#542] opened 2018-04-09 03:29 UTC
Could not import subprocess32 module, falling back to subprocess module
Node.js encountered a runtime error: module.js:538

    throw err;

    ^

Error: Cannot find module 'C:\Users\Think\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\main.js'

    at Function.Module._resolveFilename (module.js:536:15)

    at Function.Module._load (module.js:466:25)

    at Function.Module.runMain (module.js:676:10)

    at startup (bootstrap_node.js:187:16)

    at bootstrap_node.js:608:3

**Comment by victorporof** [comment] 2018-05-23 08:58
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 08:58 UTC
