### ISSUE TITLE
"Node.js was not found" when filename includes chinese

### ISSUE THREAD

**Issue by Awakening-j** [victorporof/Sublime-HTMLPrettify#279] opened 2016-02-05 02:45 UTC
I'm trying to format code for a chinese-named html file, but alert **Node.js was not found in the default path. Please specify the location.**, I rename the file to pure english, the issue was gone.  
How to fix it?  
![2016-02-05 10 46 53](https://cloud.githubusercontent.com/assets/8085088/12836664/d2674122-cbf5-11e5-8f6c-2e8460eaa66d.png)
![2016-02-05 10 46 24](https://cloud.githubusercontent.com/assets/8085088/12836667/d54e3314-cbf5-11e5-91d7-883bab146c37.png)

**Comment by victorporof** [comment] 2016-02-09 12:13
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/107

**Closed by victorporof** 2016-02-09 12:13 UTC

**Comment by QuietWind** [comment] 2016-06-29 02:17
you can use commond `which node` see your node path
