### ISSUE TITLE
Indent by editor indent setup

### ISSUE THREAD

**Issue by rustedwolf** [victorporof/Sublime-HTMLPrettify#281] opened 2016-02-11 19:45 UTC
After an update, the indentation is done according to `.jsbeautifyrc` file. Before that I could set up indentation level in my bottom right corner and the plugin indented the code by that setting. Is there a way to set up plugin to use this setting again?

**Comment by victorporof** [comment] 2016-04-08 05:42
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/33

**Closed by victorporof** 2016-04-08 05:42 UTC
