### ISSUE TITLE
space after 'async'

### ISSUE THREAD

**Issue by astanciu** [victorporof/Sublime-HTMLPrettify#513] opened 2017-12-02 19:23 UTC
before:

```Javascript
const obj = {
  mything: async (param) => {}
}
```

After:

```Javascript
const obj = {
  mything: async(param) => {}
}
```

This was fixed in jsbeautify version 1.7.4 ( https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md )

Can we upgrade the jsbeautify version? Or is there another workaround?

**Comment by gamegee** [comment] 2017-12-17 19:31
The package control currently don't match the github version.
Any news @victorporof ?

**Comment by victorporof** [comment] 2018-05-23 09:13
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/492
Will update soon!

**Closed by victorporof** 2018-05-23 09:13 UTC
