### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by eclinton3** [victorporof/Sublime-HTMLPrettify#538] opened 2018-03-17 14:46 UTC
Hello,
When I try to "prettify" my code, I receive the following error message: A runtime error was encountered in the prettifier. See the console output for more information. Do you wish to file a bug?

Any thoughts?

**Comment by victorporof** [comment] 2018-05-23 09:25
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 09:25 UTC
