### ISSUE TITLE
Sublime-HTML/CSS/JS Prettify stopped working

### ISSUE THREAD

**Issue by JohannesLyytikka** [victorporof/Sublime-HTMLPrettify#556] opened 2018-05-15 07:07 UTC
Plugin stopped working after latest Sublime text update (3.11 Build 3176)

**Comment by victorporof** [comment] 2018-05-23 08:56
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Closed by victorporof** 2018-05-23 08:56 UTC

**Comment by wggley** [comment] 2020-08-11 17:48
Stopped worked entirely since yesterday.
