### ISSUE TITLE
Use file scope instead of file extension to detect code language

### ISSUE THREAD

**Issue by hamidsafdari** [victorporof/Sublime-HTMLPrettify#305] opened 2016-04-18 02:53 UTC
Instead of specifying and using file extensions to detect the language of the file, use the **scope** of that file and prettify it accordingly. The scope of the current file is shown in sublime's status bar when you press `Ctrl+Alt+Shift+P`.

That comes in handy when I have copied a line of json from somewhere and paste it in sublime. Since the file doesn't have an extension because it is not saved yet, the plugin cannot prettify it. There are also other files that have a json structure: `.bowerrc`, `.jshintrc`, `.jscsrc`, `.sublime-package` and `.sublime-settings`. That is just an example and there are multiple other files that use the html or xml syntax. It is a burden to keep a copy of all those file extensions somewhere for this plugin. The settings are lost when this plugin is updated. That can be a good reason to do this too.

Also the path to node.js can be determined from the PATH variable. I'm guessing sublime doesn't still have the API to let developers determine that. Is that correct?

**Comment by victorporof** [comment] 2016-04-18 03:19
@hamidsafdari Thanks for the input.

First issues is a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/111

Regarding the PATH, we've had numerous problems and bug reports when trying to do it via `which node` and/or detecting environment variables. Sublime is quite buggy when it comes to what path is being used at a certain time.

**Closed by victorporof** 2016-04-18 03:19 UTC
