### ISSUE TITLE
For some reason adds a space (blank) before the quote!

### ISSUE THREAD

**Issue by dimsis** [victorporof/Sublime-HTMLPrettify#526] opened 2018-01-21 19:17 UTC
For example, check out the following HTML after prettifying it:
```
 <div class="col-md-6 text-center ">
                        <ul class="list-inline list-unstyled ">
                            <li class="list-inline-item "><a href="# ">Contact Us</a></li>
```

Can you see the SPACE before all ending double quotes?

**Comment by sahilg14** [comment] 2018-02-10 14:28
I am having the same problem. It also did that to id, causing js to fail.

**Comment by victorporof** [comment] 2018-05-23 09:20
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/492
Updating now.

**Closed by victorporof** 2018-05-23 09:20 UTC
